logging.level.org.springframework.data.r2dbc: DEBUG

spring.r2dbc:
  url: "r2dbc:postgresql://localhost/postgres"
  username: "${DB_USERNAME:postgres}"
  password: "${DB_PASSWORD:000000}"

sickness:
  groups:
    - "A00-B99"
    - "C00-D49"
#    D50 - D89:
#    E00 - E89:
#    F01 - F99:
#    G00 - G99:
#    H00 - H59:
#    H60 - H95:
#    I00 - I99:
#    J00 - J99:
#    K00 - K95:
#    L00 - L99:
#    M00 - M99:
#    N00 - N99:
#    O00 - O94:
#    P00 - P96:
#    Q00- Q99:
#    R00 - R99:
#    S00 - T88:
#    V00 - Y99:
#    Z00 - Z99: